import React from 'react';
import '../styles/globals.css'
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import PropTypes from "prop-types";

function MyApp({Component}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>React-next-test</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main} id="mainComponent">
        <h1 className={styles.title}>
          React-Next.js <Link href="/">TEST!</Link>
        </h1>
        <p className={styles.description}>
          Test를 위한 프로젝트 입니다.
        </p>
        <Component/>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

MyApp.propTypes = {
  Component: PropTypes.elementType.isRequired,
}


export default MyApp
